controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

AccueilRoute:
    path: /
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\AccueilController::index
AdminRoute:
    path: /admin

# PlaygroundRoute:
#     path: /playground/play
#     # the controller value has the format 'controller_class::method_name'
#     controller: App\Controller\GameController::index

PlaygroundSettingsRoute:
    path: /playground/settings
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\SettingsController::index